name: Build Full APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix NDK Path
        run: echo "ndk.dir=$ANDROID_NDK_LATEST_HOME" > local.properties

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Menu-APK-Hoan-Chinh
          path: app/build/outputs/apk/debug/
          
