name: Build SO Menu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Compile C++ (Fast NDK)
        run: |
          cd app/src/main/jni
          $ANDROID_NDK_HOME/ndk-build

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: File-SO-Menu
          path: app/src/main/libs/
        
